# Generated by Django 4.2.3 on 2023-07-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.CharField(max_length=256)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=10)),
                ('curso', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('data_ingresso', models.DateField()),
            ],
        ),
    ]
